# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tddbc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tddbc

  target 'TddbcTests' do
    inherit! :search_paths
    pod 'Quick', '1.2.0'
    pod 'Nimble', '7.0.2'
    # Pods for testing
  end

end
